<?php

namespace AppBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{

    // This will return a QueryBuilder instance
    public function findAll()
    {
        return $this->createQueryBuilder('c');
    }
}
