<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{

    // This will return a QueryBuilder instance
    public function findAll()
    {
        return $this->createQueryBuilder('p');
    }
}
