<?php

namespace AppBundle\Repository;

/**
 * TechnologieTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnologieTagRepository extends \Doctrine\ORM\EntityRepository
{
}
