app:
    resource: "@AppBundle/Controller/"
    type:     annotation
app_user:
    resource: "@AppBundle/Controller/User/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
avanzu_admin:
    resource: "@AvanzuAdminThemeBundle/Resources/config/routes.yml"
app_home:
    path: /

fos_user_profile_show:
    path: /profile/
    defaults: {_controller: AppBundle:User\Profile:show}
avanzu_admin_profile:
    path: /profile/edit/
    defaults: {_controller: AppBundle:User\Profile:edit}
app_user_change_password:
    path: /profile/change-password/
    defaults: {_controller: AppBundle:User\ChangePassword:changePassword}

app_user_resetting_request:
    path: /resetting/request/
    defaults: {_controller: AppBundle:User\Resetting:request}
app_user_resetting_send_email:
    path: /resetting/send-email/
    defaults: {_controller: AppBundle:User\Resetting:sendEmail}
app_user_resetting_check_email:
    path: /resetting/check-email/
    defaults: {_controller: AppBundle:User\Resetting:checkEmail}
app_user_resetting_reset:
    path: /resetting/reset/{token}
    defaults: {_controller: AppBundle:User\Resetting:reset}

